### ISSUE TITLE
Open qgis2web webmap on iphone or android device

### ISSUE THREAD

**Issue by ptycharly** [tomchadwin/qgis2web#1013]
First I would like to think for the development of this plug in. I don't know if it's the good place to present the issue and i will remove it in case not.

I have no problem to read my webmap on a computer via web browser but on an ios or android device I can't. Is there a method to do it?

I use the 3.16 qgis2web version

Think for your help

**Comment by andreaordonselli** [comment]
Hello,
qgis2web exports everything to a local folder and by opening the index.html file with a computer desktop you will be able to see the map because all the javascript resources are loaded. 
If you transfer this folder to a mobile device you will not be able to see the map because the mobile device is unable to load javascript assets.
You will need to copy your entire folder, which represents a static site, into a website with a domain that you have purchased or that is provided to you for free.
Search for "website free" with google and find the one that's right for you.
PS: you must be able to copy and paste all the folder created by qgis2web into this site and then visit it from your mobile devices by link like https://www.freesiteexample.abc/foldercreatedbyqgis2web/index.html

**Comment by ptycharly** [comment]
Hi, many thanks!
I was looking to use the web map locally and independently on a smartphone without going through a third-party server. As the mobile device is unable to load javascript assets I will test your solution. Thanks again!

**Comment by andreaordonselli** [comment]
Remember that with your browser you can open the console with the F12 key and then set a smartphone or table view with this button.
![2022-10-14 10_07_59-Window](https://user-images.githubusercontent.com/89784373/195796170-61fd9207-037a-4090-b224-d5c1a44ab398.png)

So you can design your webgis and see it in action using a desktop computer but as if you were viewing it with a mobile device.

![image](https://user-images.githubusercontent.com/89784373/195796096-208dacfe-a408-4c8f-b0cb-40be09944798.png)

**Comment by ptycharly** [comment]
Ok, noted.
Thank you!
