### ISSUE TITLE
In qgis2web two layers overlap hiding each other despite being seen in QGIS

### ISSUE THREAD

**Issue by jmgomesp** [tomchadwin/qgis2web#1032]
To ensure no time or effort is wasted in bug reporting, please follow these steps:

1. Make sure you are using the latest release of qgis2web
2. Check the issues on Github to see whether the bug has already been reported, and if so, read through all the comments on the issue, and add any additional information from your experience of the bug
3. Make sure you can reproduce the bug reliably
4. Reduce the complexity of your bug conditions as far as you can, especially by reducing the number of layers, ideally to one
5. Raise a Github issue, including:
  - only one bug per Github issue
  - the qgis2web version (or make it clear you are using Github master branch)
  - any Python error text/stack trace which occurs
  - browser JS console errors - press F12 in qgis2web to open the developer toolbar and find the console
  - screenshot of your settings
  - screenshot of the output
  - a link to the data you used, if possible

**Comment by jmgomesp** [comment]
Hello, 

Thank you for your attention. 

It must have been a couple of years since we made a map using QGIS2WEB and we managed to overlay two layers without problems. The first layer was a smaller circle than the second layer and they both looked perfectly. However, at the moment I am trying to achieve something similar and it is impossible for me. No matter how many attempts I make, the first layer, even being smaller than the second, hides this one. I put the link of the web map that was created at that time and the result that I get now.

Obviously, we want the two circles to be seen at the same time, like in this map. 

https://www.upo.es/facultad-ciencias-sociales/es/fcslab/mapa-areas-influencia-centros-educativos/  

![Capturaejemplo](https://github.com/tomchadwin/qgis2web/assets/135820268/f79874f6-c17c-4a92-85db-87190d1e3a73)


We would be delighted if you can give us an answer because we have been trying to get out of this problem for a long time, using different options, but without success.

Thank you very much and congratulations for your amazing pluggin!!

**Comment by andreaordonselli** [comment]
Are you able to publish your qgis project or your qgis2web export?
If you turn off the layer with the small circles on the map, is the layer with the large circles visible?
Can you consider exporting openlayers or do you really want to export with leaflets?

**Comment by juanmiguelgomez** [comment]
Thank you very much, Andrea!! 
I will answer: 
- Yes, I have no problem with qgis but I have problems with qgis2web, as the photo shows. 
- If I do not select the first layer, you can see the big points perfectly
- I was exporting oppenlayers. After your suggestion, It works using leaflets (however, two years ago it worked using openlayers). A second question arrises when I use leaflets:  if I I use triangles or squares for the back layer, they are converted on circles. So, instead a triangle and a circle inside this triangle, map shows a circle inside another circle. 
- 
![image](https://github.com/tomchadwin/qgis2web/assets/134065564/aa862da1-3e25-4989-bdd1-d963d9094c8e)


![image](https://github.com/tomchadwin/qgis2web/assets/134065564/eba59faa-5da4-418b-ad12-7e2fdb96c080)

Thanks again!! Regards. JM.

**Comment by andreaordonselli** [comment]
I struggle to help you with images only, my first request in the last post meant: can you create a zip of your qgis project and post it here as an attachment? 
Then sorry, but I didn't understand if you are forced to export with leaflets or you can also consider exporting with openlayers and you are simply interested in making the project work on the web.
Finally, if you can't publish the qgis project can you provide a link to the new webmap that doesn't work?  I would like to see the browser console if it shows any errors.

**Comment by jmgomesp** [comment]
Hi, Andrea!! And thanks again. EI am trying to export the project using QConsilidate3 but it is not possible. I realize that it may be the problem I have with qgis2web (in openlayers). Let me show in a video what happens because it may be easy for you.  
When I try to use qgis2web (openlayers)  and when I try to export my project in a package ...
https://drive.google.com/file/d/11rKhH6N4BAqAsWSK8LVhV-mIKxaWUxws/view?usp=sharing

When I try to use  qgis2web (leaflet)...
https://drive.google.com/file/d/1SWTDNbps8jst54-v5Ebr5X6eadyEXdH2/view?usp=sharing

Have you got some idea about the problem about my exportation? 

Thanks a lot. Regards. JM.

**Comment by jmgomesp** [comment]
Hi, 
Yes, it works ok with  leaflet, although the shapes of icons in web are different regarding the shape in qgis (the square, for example, become a circle) 

I leave a link to GeoPackeage file. I hope it works: 
https://drive.google.com/file/d/1e2Gw62hAX43jR9nwnjlfq03MU6Yon-x9/view?usp=drive_link

Thanks a lot. JM.

**Comment by andreaordonselli** [comment]
I think you don't have the latest version of the plugin. Try updating qgis2web.
Leaflet export does not support graphic shapes, you would have to export and then manually edit the code to write your own. I'm not an expert on leaflets but I'm sure you can find something by searching the web.

As for openlayers the result is excellent. This is the initial export:
![2023-06-13 16_10_27-Film e TV](https://github.com/tomchadwin/qgis2web/assets/89784373/56f261e7-fa38-472f-9b5b-81af0419c473)
Here's a zoom:
![2023-06-13 16_11_03-Film e TV](https://github.com/tomchadwin/qgis2web/assets/89784373/e87d607b-3d7d-4e41-93fe-6970407fd4cc)

You don't see all the features because in the layers.js file the layers are configured as `declutter: true`, it means that the overlapping features won't be seen until you zoom in.
Editing the layers.js file by hand writing `declutter: false` here is the result:
![2023-06-13 16_09_51-Film e TV](https://github.com/tomchadwin/qgis2web/assets/89784373/aece72dc-b25c-4d3c-b951-26dded4fbf3d)
You don't see all the features because in the layers.js file the layers are configured as declutter:true, it means that the overlapping features won't be seen until you zoom in.
Editing the layers.js file by hand writing `declutter: false` here is the result:
![2023-06-13 16_10_18-Film e TV](https://github.com/tomchadwin/qgis2web/assets/89784373/ec5201d8-688e-487a-a307-134f3535065e)

Ti allego i 2 progetti esportati
[openlayers declutter false.zip](https://github.com/tomchadwin/qgis2web/files/11735862/openlayers.declutter.false.zip)
[openlayers declutter true.zip](https://github.com/tomchadwin/qgis2web/files/11735863/openlayers.declutter.true.zip)

While zooming and panning the project is quite slow I think because there are so many points. Maybe you can search the web for some tricks to speed up openlayers with lots of geometries.
I think the slowness problem is generated by the `ol.style.RegularShape` style of the geometries.
I hope I was helpful

**Comment by jmgomesp** [comment]
Brilliant!! Thank you very much. Now it works perfectly!!! Regards. JM.

**Comment by andreaordonselli** [comment]
I'm glad that qgis2web is in line with your expectations. Close the issue if it's resolved. Thank you.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
