### ISSUE TITLE
Scale Dependent Visibility in OL3 prevent export of html

### ISSUE THREAD

**Issue by jbosma4** [tomchadwin/qgis2web#168]
When choosing the option for Scale-Dependent visibility for layers to publish, the preview shows no map. Upon export, the web browser opens, but goes nowhere and no html file is created

**Comment by tomchadwin** [comment]
Yes, I'm getting that as well. Not sure what's causing it, but it could well be the conversion from scale to resolution, which I was never sure of. It currently does the following:

```python
minRes = 1 / ((1 / layer.minimumScale()) * 39.37 * 90.7)
maxRes = 1 / ((1 / layer.maximumScale()) * 39.37 * 90.7)
```

@volaya, does this look right to you?

**Comment by tomchadwin** [comment]
OK, perhaps this is working after all. When you export your map, can you try zooming in and out a bit to see if the layer in fact appears at certain zoom levels?

**Comment by jbosma4** [comment]
I've published the map and yes, the layers appear at different zoom levels, but I have set certain layers to appear at varying zoom levels and that setting has been removed after publication. Instead, all layers appear at all zoom levels.

**Comment by tomchadwin** [comment]
I don't quite follow:

> I've published the map and yes, the layers appear at different zoom levels

>  that setting has been removed after publication. Instead, all layers appear at all zoom levels

Don't these two sentences contradict each other? I'm not trying to be difficult, just to understand precisely how to recreate the issue.

I've opened two layers in QGIS, and given them different scale-dependent visibility. This persist into the OL3 map exported by the plugin.

Or do you just mean that the checkbox "Use layer scale dependent visibility" does not remain checked when you reopen the plugin? If this is the issue, try starting the plugin, checking that box, closing the plugin, and saving your project. See if that fixes it.

**Comment by jbosma4** [comment]
I apologize for the confusion. If I don't select the Use Layer Scale Dependent Visibility option, the map publishes, but all layers are visible at all levels (even though I set scales on all the layers). If I select that option, no html file is created and I cannot see the map.


I tried your suggestion and the result was that the Use Layer Scale Dependent Visibility option did not remain checked.


Here are the steps that I used after:

1. Set independent scale visibility ranges for layers (this allows my point layers to appear at a lower level, rather than on all levels)

2. Save project

3. Open plugin

4. Nothing is altered in the Layers and Groups section. I changed the export folder to a local folder for this project. Use Layer Scale Dependent Visibility is checked. OSM Standard map is selected. OpenLayers3 is auto-selected.

5. Select Export

6. Internet Explorer opens (not my default browser, Google is), but it just goes to my home page. The folder that I created only has the following folders within it: Layer,s Resources, and Styles. There is no html file.


Does that help?


Jessie Bosma
Client Technical Support & GIS Analyst
________________________________

jbosma@ecnetwork.com<mailto:jbosma@ecnetwork.com>
Emergency Communications Network
780 W. Granada Boulevard, Suite 200
Ormond Beach, FL 32174
866-939-0911
www.ecnetwork.com<http://www.ecnetwork.com/>
ECN Cares: Tell my manager how I'm performing<mailto:ecncares@ecnetwork.com?subject=Re:%20CodeRED>


________________________________

**Comment by tomchadwin** [comment]
Thanks for the precise explanation. At this stage, I cannot recreate the issue. How many layers are selected for export? I would try trying each individually in turn to see if the problem lies with one layer. I'm also very confused by IE opening rather than Chrome.

What happens in the plugin preview pane when you click "Update preview" with scale-dependent checked?

If you are able to send me your layers, I can try to recreate the issue, but at the moment, I'm struggling to be able to fix this one.

By the way, al layers appearing at all scales is correct if the scale-dependent checkbox is unchecked. I've been considering removing that checkbox, and always honouring layers' scale-dependent visibility. However, it seems I can't make that change until we can work out what this problem is.

**Comment by jbosma4** [comment]
Tom,


I removed all of the layers and slowly started to add them back into the publication process. It helped me find the "bad" layer and the scale visibility is working again. I'll recreate the bad layer and let you know if the problem persists.

Jessie Bosma
Client Technical Support & GIS Analyst
________________________________

jbosma@ecnetwork.com<mailto:jbosma@ecnetwork.com>
Emergency Communications Network
780 W. Granada Boulevard, Suite 200
Ormond Beach, FL 32174
866-939-0911
www.ecnetwork.com<http://www.ecnetwork.com/>
ECN Cares: Tell my manager how I'm performing<mailto:ecncares@ecnetwork.com?subject=Re:%20CodeRED>


________________________________

**Comment by tomchadwin** [comment]
OK, great. If you can't identify anything in that layer as being bad, give us some details (or ideally upload it somewhere so we can take a look at it). If the plugin is not handling a legitimate layer, it needs to be looked at. I'll close this for now, and we can open a new issue about that layer if we need to.

**Comment by jbosma4** [comment]
Will do. Thank you for your quick response! I appreciate you looking at this (even if it does seem to be on my end).


Jessie Bosma
Client Technical Support & GIS Analyst
________________________________

jbosma@ecnetwork.com<mailto:jbosma@ecnetwork.com>
Emergency Communications Network
780 W. Granada Boulevard, Suite 200
Ormond Beach, FL 32174
866-939-0911
www.ecnetwork.com<http://www.ecnetwork.com/>
ECN Cares: Tell my manager how I'm performing<mailto:ecncares@ecnetwork.com?subject=Re:%20CodeRED>


________________________________

**Comment by tomchadwin** [comment]
No problem at all - as I say, just because the layer causes an error, it doesn't mean the layer is at fault. It could simply be something the plugin cannot yet handle. By the way, if this is the same issue as on GIS.SE? http://gis.stackexchange.com/questions/176902/when-using-the-qgis2web-plugin-openlayers3-option-no-html-file-is-created

**Comment by jbosma4** [comment]
Yes. I was trying to find the best platform to enter the issue.


Jessie Bosma
Client Technical Support & GIS Analyst
________________________________

jbosma@ecnetwork.com<mailto:jbosma@ecnetwork.com>
Emergency Communications Network
780 W. Granada Boulevard, Suite 200
Ormond Beach, FL 32174
866-939-0911
www.ecnetwork.com<http://www.ecnetwork.com/>
ECN Cares: Tell my manager how I'm performing<mailto:ecncares@ecnetwork.com?subject=Re:%20CodeRED>


________________________________

**Comment by tomchadwin** [comment]
Of course. I'll add a comment there pointing to here.

**Comment by mykolakozyr** [comment]
If you don't mind I join your conversation.
In 1.0.0-RC2 release it is written: "Scale-dependent visibility widget removed from GUI...". Firstly I thought that the plugin started to use it by default, but it seems like it doesn't (or smth is wrong with my layers).
Could you please write if it's going to be added later or not and suggest another options to add this feature.
Thank you in advance

**Comment by tomchadwin** [comment]
It is meant to use it automatically for any layers which have it set in QGIS. It doesn't work for you?

**Comment by mykolakozyr** [comment]
no, I used leaflet and tried both vector and rastr data

**Comment by tomchadwin** [comment]
I'll check it tomorrow. You are setting it in QGIS via Layer > Properties > General?

**Comment by mykolakozyr** [comment]
It looks like the problem (kind of a problem) was the following (I used Leaflet):
map shows all layers even those which has to be at bigger zooms. However, when I zoom in and zoom out to certain zoom level it "fixes" and then layers apear only when they "have to". 
Besides, you should check the correspondence between QGIS scale and zoom level. With OL3 it's OK, but it doesn't work well here. It's not a problem to change it in the index file, but still it looks like there is a mistake somewhere.

**Comment by tomchadwin** [comment]
OK, let me see if I can summarize what you are saying:

- on initial map load, all layers display, even if they should not because of scale-dependent visibility
- when you start to zoom in and out, layers do start to appear and disappear correctly
- however, the precise zoom level at which they appear and disappear is not quite correct

Is that an accurate description of what you are seeing?

**Comment by mykolakozyr** [comment]
Yes, you are right, but I also met with other problems. I've created maps using Leaflet and OL3 and want to describe what I've got:

### Preconditions:
I have 5 vector and 5 raster layers, which have to be displayed at different zooms (12-16+ (1 vector and 1 raster per zoom and the last (16) stays till the end), 1 vector layer (border), which has to be displayed all the time and another vector layer (Photo Location), which is also has to be displayed at 16+ zoom.
All Layers, Project and General Properties have EPSG: 3857
Due to the preconditions I expected [this map] (http://geoteam.hol.es/qgis2web/expected/)

### Results:

### 1. OL3 
Plugins created the [map] (http://geoteam.hol.es/qgis2web/OL3/)

Vector layers work perfect.
Raster layers don't have scale dependancy and they look reprojected.
Layers list doesn't change anything (see leaflet)

Solution: 
- save .tiff images as .png (using graphic editor) 
- change reprojected images in the directory into created .png files
- add minResolution and maxResolution data about rasters in layers.js

Another annoying thing: layers' names with the same digit saves with first only (so if I have names "99" and "999", it save only one layer with the name "9"). Digit "0" doesn't saves at all (I had layers 100 and 1000, it saved the file "1")

### 2. Leaflet 

Sometimes I have an error, but not all the time: 
![373](https://cloud.githubusercontent.com/assets/17071295/12900690/53b6f80e-cec0-11e5-9294-d12e28e853c6.png)
2.1 To make the map easier (It takes a lot to show the map with all the layers) here are two maps with one scale dependant vector layer (layer has to appear at zoom 15):
   2.1.1 [With the List of Layers] (http://geoteam.hol.es/qgis2web/simpleleafletlist). Vector scale dependant layer doesn't appear at first. If I check in and out the layer in the list it appears, but the scale dependance doesn't work. 
   2.1.2 [Without the List of Layers] (http://geoteam.hol.es/qgis2web/simpleleaflet). And here it is:

> on initial map load, all layers display, even if they should not because of scale-dependent visibility
> when you start to zoom in and out, layers do start to appear and disappear correctly

The third point 

> however, the precise zoom level at which they appear and disappear is not quite correct

is a bit different: I set scale dependence at 1:15000 (non included) to 1:1 (zoom level 15+), but in index.html it was up to "14".

2.2 However, I created the "needed" [Leaflet map with layers list] (http://geoteam.hol.es/qgis2web/leafletwithlist/)
Vector problems are the  same as above.
Raster files don't appear at all. However they exist in data folder, but they are empty. Changing images as I did with OL3 doesn't help.
2.3 [The map with all the layers without list] (http://geoteam.hol.es/qgis2web/leaflet/) doesn't work well at all.

It seems like that's all. 
I hope my comment could help to develop the plugin if needed (It could be problems with my computer).
Thank you one more time for a quick response.

**Comment by tomchadwin** [comment]
I'll try to look into this. You are raising quite a lot of issues, not all of which I yet fully understand. I might open separate issues for individual bugs you have identified. I'll cross-reference them to this issue, though, so hopefully you can keep an eye on progress.

**Comment by tomchadwin** [comment]
@mykolakozyr : "Raster layers [...] look reprojected"

Rasters are reprojected to EPSG:3857, because the exported maps use that projection. I'll raise another issue to try to use the project projection for raster layers if "Match project CRS" is checked.

**Comment by tomchadwin** [comment]
@mykolakozyr: "layers' names with the same digit saves with first only (so if I have names "99" and "999", it save only one layer with the name "9"). Digit "0" doesn't saves at all (I had layers 100 and 1000, it saved the file "1")"

I can't recreate this, or I am not understanding the issue properly. Can you explain it further?

**Comment by tomchadwin** [comment]
Closing for now, because of no recent feedback. Reopen if required.
