### ISSUE TITLE
ECW dumps QGIS?

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#220]
See http://gis.stackexchange.com/questions/183631/qgis2web-crashes-latest-qgis-2-14

I don't have any ECWs, so cannot test. Can anyone recreate this issue? If so, can anyone help fix it?

**Comment by johnwbryant** [comment]
will check this out tomorrow, I have a few ECWs up my sleeve

**Comment by philipjohnbarlow** [comment]
Tom, I've had a go with a few ECWs just now and I've had no problems at all (example below).  I suspect the problem that goatwillow is the raster conversion from ECW to PNG?  The error message looks to be related to the progress bar that appears at the top of the canvas when the plugin is loaded.  The first thing I would checks is that they have the correct path to GDAL tools under raster>GDALTools settings

![ecw1](https://cloud.githubusercontent.com/assets/14541141/13816746/823fc776-eb87-11e5-9e2e-854a8b461743.PNG)

**Comment by johnwbryant** [comment]
I did a quick test here:

-created a QGIS project with a smallish (17MB)  ECW, a WMS layer, and a WFS layer
-opened the same project in QGIS 2.8.7 and 2.14.0
-ran the qgis2web export to OL3 from each version of QGIS, with identical settings

Both came out the same, though it took a little while. ECW converts to PNG ok in both cases.

For my immediate use cases, it would probably make more sense to publish the ECW as a WMS and connect to it that way, rather than duplicating storage of images.

Great plugin!

**Comment by tomchadwin** [comment]
I'll close this for now, as there has only been this one instance of the problem. Will reopen if others experience it.
