### ISSUE TITLE
Suggestion: Transparency sliders for layers

### ISSUE THREAD

**Issue by Zeitsperre** [tomchadwin/qgis2web#263]
One feature that's prominent on many web-gis interfaces is an adjustment slider for transparency when overlaying multiple polygon datasets. Setting static transparency with QGIS translates well into generated qgis2web maps but It would be interesting to see this adjustable functionality in OL3/Leaflet.

**Comment by tomchadwin** [comment]
If this can be implemented as part of the layers list in each library, then I agree that this would be useful, so long as it is optional. Can anyone implement an alpha slider in the Leaflet or OL3 layers list generated code?

**Comment by tomchadwin** [comment]
I'm going to close this one for now. It cannot be implemented in Leaflet at the moment:

https://github.com/Leaflet/Leaflet/issues/5116

**Comment by gregrowles** [comment]
Guys, why close it if it's a known flaw?

**Comment by tomchadwin** [comment]
Because it doesn't make sense to implement a hack which will have to be unpicked if the upstream bug is fixed. My Leaflet PR has not been merged, so I conclude that the Leaflet devs dint see the issue as high priority. 

By the way, neither playground changes opacity for me (Chrome/Android). Or were the playgrounds just to illustrate the slider itself? I've not looked closely at the code - not v easy on mobile.

**Comment by gregrowles** [comment]
Hi Tom, no baseLayer object manipulation is taking place (i've tested and implemented in my web application though) but not on playground. 2nd link outputs console values when adjusting slider but I'm a newbie on gitHub (my 'edits' to leaflet.js are only on my local copy only, i tried posting changes but don't have enough experience to share the updates correctly). Edits were made to _onInputClick and _checkDisabledLayers.

The use of this._form.getElementsByTagName("input") is extremely generic (assumes all controls in the baseLayer collection are checkbox items). I initially added code to ignore type=range but ended up using (this._getLayer(t.layerId) != undefined) so that any control that is not recognized as a 'layer' are ignored

[leaflet_dot_js_edit_gtr20170217.txt](https://github.com/tomchadwin/qgis2web/files/782578/leaflet_dot_js_edit_gtr20170217.txt)

**Comment by gregrowles** [comment]
OK, i really suck at public domain code-running sites (I tried creating a new bin but failed horribly, linking my .js files directly from gitHub). I created a fork, have a modified version of leaflet.js working (accepting boolean parameter 'opacitySlider' and creating & adjusting background opacity for baseLayers):

https://github.com/HISPSA/focus-for-impact/blob/master/js/leaflet.js

I also tried updating a copy of [Control.Layers.js] here: https://github.com/HISPSA/Leaflet/blob/master/src/control/Control.Layers.js

**Comment by IvanSanchez** [comment]
> My Leaflet PR has not been merged [...]

@tomchadwin I think you didn't finally submit a PR for Leaflet/Leaflet#5116? Correct me if I'm wrong.

@gregrowles I see something that I really really like about https://github.com/HISPSA/Leaflet/commit/9cec1c0dbf3b3db287df0ca21d910ba3bb7315b7 , and it's the `if (inputs[i].className == 'leaflet-control-layers-selector'){` check. That alone could fix Leaflet/Leaflet#5116, I think. Or replacing the `getElementsByTagName()` call with a `querySelectorAll()`.

I don't think we want to have an opacity slider in core Leaflet, but I think it would make a good plugin. Fixing the upstream bug should make that much less prone to bugs.

**Comment by gregrowles** [comment]
OK, looks like i've made a contribution to team leaflet ;) 
@tomchadwin alpha slider implemented: Yes, optional: Yes

**Comment by tomchadwin** [comment]
@IvanSanchez Please accept my apologies. I misremembered how things stood. Because I could not get my changes to work with the playground, I didn't make a PR. I therefore left it at that. I know others said they could get my changes to work, and that they looked correct, but without being able to get it to work myself, I didn't think a PR was appropriate.
