### ISSUE TITLE
Qgis2web .tif raster has black line

### ISSUE THREAD

**Issue by Echbart** [tomchadwin/qgis2web#267]
Im using latest Qgis Essen with latest Qgis2web plugin. I import my .tif raster of filtered and visualized LiDAR data and I get at top and bottom of raster a black band. 

MY raster and project CRS is Slovene National Grid (SNG) EPSG: 3794. I guess it has to do something with plugin not supporting SNG. When i check Match Project CRS nothing happens.

Here is picture showing the issue.
![qgis2web](https://cloud.githubusercontent.com/assets/18083001/15093078/849492ae-147c-11e6-8998-c04ea4365a19.jpg)

And .tif raster only works with leaflet, openlayers3 dont show it when i check some map for background.

**Comment by tomchadwin** [comment]
The exported map is in EPSG:3857, which is why the raster is skewed. Try "Match project CRS", though this will stop basemaps from displaying, as they are only available in EPSG:3857. As I mentioned on StackExchange, I'm not sure rasters are properly reprojected, though. We need to see what happens.

**Comment by Zeitsperre** [comment]
As a workaround for the raster issue (and because it's generally quicker to render), I've been using Qtiles to generate a TMS-formatted slippy map overlay and then adding that directly into QGIS2web data folders and index files. I'd suggest adding this as an option for handling/processing rasters but I have zero experience in plug-in development.

**Comment by tomchadwin** [comment]
Automatic tiling has been requested before, and I've said no because other plugins do it. Out of interest, how do you add the tiled layer into QGIS? I've been wondering about whether it would be possible to detect non-WMS tiled layers, and import them automatically. However, because tileserver layers are not a native QGIS layer format, I've not pursued it any further.

Any ideas welcome.

**Comment by Zeitsperre** [comment]
It's handled the same way as if adding a basemap. The Qtiles formatting adds the .png directory using L.tileLayer('file:address/here/{zoom}/{x}/{y}') and then uses L.control.layers to add them in as overlays. I've been using that plugin as it preserves raster styling and doesn't create any black NULL area borders.

I typically add my overlays in as an additional basemap just after 'map' is defined since the extents I show are fairly complete (they're usually climate geometries). I usually just modify the Qtiles output to match the Qgis2web styling:

`var basemapX = L.tileLayer('file:address/to/tiles/{z}/{x}/{y}.png', {
        maxZoom: 10,
        attribution: 'Generated by QTiles',
	tms: true,
      	});
	basemap2.addTo(map);`

As you can tell, I'm very new to this. Hope this helps.

**Comment by tomchadwin** [comment]
No, how are the layers added in *QGIS*, not Leaflet. I want to know so we could consider detecting them automatically and building them in the export.

**Comment by Zeitsperre** [comment]
Ah, I haven't been adding the slippy maps back into QGIS, though TileLayersPlugin boasts that it can handle local directories of WMS tiles using a simple definition file. Again, I haven't used that plugin. Sorry!

**Comment by tomchadwin** [comment]
Oh, I see. Apologies for misunderstanding. Still think it could be possible... Thanks.

**Comment by Echbart** [comment]
It has to do with CRS. Match CRS wont work. Also when i wrap raster in QGIS from EPSG: 3794 to  EPSG:3857 i get skewed raster. Will post solution in workarounf when i find it.

**Comment by tomchadwin** [comment]
Closing, as I believe this is functioning as expected - rasters warped to 3857.

**Comment by tomchadwin** [comment]
@Zeitsperre By the way, native tilemaps are coming soon to QGIS - https://github.com/qgis/QGIS/pull/3473. Once it's released, that gives us the option of completely getting rid of basemaps in qgis2web.

**Comment by tomchadwin** [comment]
Assuming everything has Python bindings, of course.
