### ISSUE TITLE
Better replication of QGIS styling in Leaflet

### ISSUE THREAD

**Issue by magerlin** [tomchadwin/qgis2web#268]
In the produced Leaflet maps lines are thinner and point markers are smaller than in the original QGIS map: 
![screenshot 2016-05-09 13 19 36](https://cloud.githubusercontent.com/assets/1887531/15111776/adbd7c90-15e9-11e6-9998-81dadd607cf8.png)

And point markers are missing the black border they had in QGIS.

**Comment by tomchadwin** [comment]
Yes, it's a long-standing issue. If you are able to help, I'd appreciate it. Open `leafletScriptStrings.py` in a text editor, and search for the string `* 4` - there are multiple instances (Tom = bad coder). Change the `4` to other values to see what works best. Use the QGIS plugin `Plugin Reloader` so you don't have to restart QGIS each time you make a change.

One thing to note - the plugin doesn't differentiate between the different QGIS units - see #144 - so let's concentrate on getting millimetres right first, since it's the default. We can then get rid of the multiplier when units is set to pixels.

**Comment by magerlin** [comment]
I'll take at look at it :-)

**Comment by tomchadwin** [comment]
Thanks you - it's very much appreciated. I've just never found the time to sort this one out...

**Comment by magerlin** [comment]
I been playing with it, but I think there is a fundamental problem with writing:

                     borderWidth=borderWidth * 4, as you do in line 264

I can change  4 to any number even zero and nothing happens. But writing borderWidth= 2 changes the border width.

Writing  radius = radius * 4 in line 262 makes the whole map disappear, while writing raduis = 15 makes nice big circles.

I have no experience in Python so I cannot get any deeper into this I think.

**Comment by tomchadwin** [comment]
OK, I'll see if we can look into it at some stage - thanks for the initial thoughts.

**Comment by tomchadwin** [comment]
Can you try current master after @boesiii's commits this morning? Let us know if that improves things a bit (single style polygons only).

**Comment by tomchadwin** [comment]
What we need to do is spin all those `* 4`s into a function. We can then tweak the value more easily, and also perhaps add in different behaviour for `mm` versus `px`.

**Comment by boesiii** [comment]
Tom, I have something for the * 4.  I will make a pull request today sometime.

**Comment by tomchadwin** [comment]
You, Sir, are a gentleman and a scholar. Hope you noticed https://github.com/tomchadwin/qgis2web/commit/3f97ee78986925e129a1329e82ca89bb713517d0.

**Comment by tomchadwin** [comment]
@boesiii Did you ever make a PR for this?

**Comment by boesiii** [comment]
No I haven't.

I have not figured the correct process to use github correctly so that making a PR is easier.

**Comment by tomchadwin** [comment]
I hope this issue is now reolved. Reopen if not.
