### ISSUE TITLE
How to deal with very large datasets

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#307]
Q2W does not work well with large datasets and I have been thinking about how solve the issue.  Maybe vectors tiles?  Maybe this: https://github.com/mapbox/geojson-vt

**Comment by tomchadwin** [comment]
Perhaps. I'd like to handle vector tiles if they are the source of a QGIS layer. Not looked at that yet.

**Comment by tomchadwin** [comment]
I shall close this for the moment after recent commits - see https://github.com/tomchadwin/qgis2web/issues/300#issuecomment-272451649.

As for vector tiles, I'm not going to pursue this for the moment, since I don't beloeve they are supported in QGIS - correct me if I am wrong.

I'll therefore close this issue - reopen if required.
