### ISSUE TITLE
Trailing comma if no layer attributions

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#411]

**Comment by tomchadwin** [comment]
I think this is because the code lazily and incorrectly sets a layer's attribution to:

```html
<a href=""></a>
```

if no attribution is set in QGIS.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by tomchadwin** [comment]
Issue has recurred (#676)

**Comment by Jeroen-GroeneBij** [comment]
Thanks for pointing out that this actually shows the name and url taken from the metadata tab of the layer. This might be a good addition to the wiki.

However:
Just entering a name and no url will show the name as link and linking to the location of the index.html as created by qgis2web. I do not like that. When I just enter a name and leave the url field blank, it should, in my opinion, just show that name as plain text.


I have done some testing on the trailing comma issue (only tested in Leaflet) and the effect is also somewhat irregular and unexpected:

- A map with just one layer, including name and url will show the name as link, with the one comma (qgis2web, name). This looks perfectly fine to me. 
- A map with multiple layers, with a random layer having a name and url, will show that name as link, but now has two comma's in front of it (qgis2web, , name). 
- A map with multiple layers, with two random layers having a name and url, will show both names as link, also has two comma's in front of it and it is in reverse order (qgis2web, , name2, name1). So the upper layer is put at the end. That seems weird to me, since the top layer is probably the most important one.
- A map with multiple layers, with two random layers and the bottom layer having a name and url, will show all three names as link, but shows two comma's after the bottom layer name and it is in reverse order (qgis2web, bottom, , name2, name1).
- A map with multiple layers, with two random layers and the bottom two layers having a name and url, will show all four names as link, but shows two comma's after the second to last name and it is in reverse order (qgis2web, bottom, second to last, , name2, name1).

So it seems with multiple layers, you will always end up with , , somewhere in between the names.

In all cases, unchecking a layer in the legend (layers list) will remove the name and adding it again when checking the layer again. That seems very appropriate to me.

I hope this will help in finding a solution.

**Comment by riccardoklinger** [comment]
so is this fixed now @tomchadwin ?

**Comment by tomchadwin** [comment]
I think it's fixed, yes. @jukos, feel free to post your other attribution issue(s) in a new ticket, as I'll close this one.
