### ISSUE TITLE
Leaflet measure is not displaying any measurements

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#457]
When using the Leaflet measure option there is no measurement output and there are no errors in developer tools.

**Comment by tomchadwin** [comment]
This is odd. Chrome console shows nothing, but the qgis2web preview pane console shows:

TypeError: 'undefined' is not a function (evaluating 'function(){this._disableMarkers=!1}.bind(this)')

Needs further investigation. I recently upped the measure plugin version (and the dram plugin on which it depends). Has it worked since then?

**Comment by boesiii** [comment]
not sure

**Comment by tomchadwin** [comment]
I can't figure out the problem. I'm considering switching from leaflet-measurecontrol to leaflet-measure. I hoped that would also fix another issue, but it doesn't seem to yet:

https://github.com/ljagis/leaflet-measure/issues/54#issuecomment-290412671

**Comment by tomchadwin** [comment]
The second issue has been resolved with the other plugin. I'm therefore ready to switch from Leaflet.measurecontrol to leaflet-measure. Will update here when it's done.

**Comment by tomchadwin** [comment]
Switched to leaflet-measure. Not yet fully tested, but will close this. Reopen if problems.
