### ISSUE TITLE
Support wmts

### ISSUE THREAD

**Issue by frank0815** [tomchadwin/qgis2web#514]
Hello,

is there any possibility to add wmts layers with the export? Or maybe in the future?

Thanks and regards
Frank

**Comment by tomchadwin** [comment]
It's supported already. Do you have an example which doesn't work? Pay attention to layer and project CRSes, and the plugin setting "Match project CRS".

**Comment by tomchadwin** [comment]
It was introduced in 2.10.0:

https://github.com/tomchadwin/qgis2web/releases/tag/v2.10.0

**Comment by frank0815** [comment]
Hello Tom,

thanks for the quick answer. I’m trying to add a mapbox layer to a webmap. In Qgis (EPSG 3857, no 'on the fly' CRS transformation) I can see the mapbox wmts layer. When I’m  export the map to a leaflet or open layer map the tiles are not visible but the layer is shown on the layerlist. Hope you’ve got an idea.

Many thanks and regards
Frank

Von: Tom Chadwin [mailto:notifications@github.com]
Gesendet: Mittwoch, 28. Juni 2017 23:59
An: tomchadwin/qgis2web <qgis2web@noreply.github.com>
Cc: Jaeger, Frank SDO-DMS/65U <frank.jaeger@shell.com>; Author <author@noreply.github.com>
Betreff: Re: [tomchadwin/qgis2web] Support wmts (#514)


It's supported already. Do you have an example which doesn't work? Pay attention to layer and project CRSes, and the plugin setting "Match project CRS".

**Comment by Csrtlp** [comment]
Not sure if this issue is related but had the same issues exporting WMTS layers through qgis2web/Leaflet.

Noticed the following: 
When qgis2web exports the wmts layer, the url is 'shortened by 1 letter'. As in the 'wmts' gets cut to 'wmt'
Export qgis2web: layer_X = L.tileLayer.wmts('https://url/wmt',{...}); --> does not work
manually adding the s to wmts in the end solved the issue. 

qgis2web Installed version	3.16.0
