### ISSUE TITLE
Add a WMS layer to the basemaps in leaflet

### ISSUE THREAD

**Issue by boesiii** [tomchadwin/qgis2web#521]
I have a WMS layer which serves aerial imagery.  I would like the layer to show up in the basemaps list in a leaflet map.

**Comment by tomchadwin** [comment]
I remember looking at this when I first got involved with qgis2leaf. It's not currently supported, but it could be done. Look at `basemaps.py`, and you'll see the Leaflet basemap URLs are just that - just the URLs. Now look at:

https://github.com/tomchadwin/qgis2web/blob/master/leafletScriptStrings.py#L176

So the script automatically surrounds the URL with the code to make a `L.tileLayer()` out of it.

Therefore, in order to support other layer types as basemaps, take the `L.tileLayer()` bit out of `leafletScriptStrings.py`, and put it into `basemaps.py`, around every existing basemap. You can then add your own other layer types in there, such as L.tileLayer.WMS. This is how the OL basemaps code currently works, I believe.

Think you are up to it? I can't look at this at the mo - apologies.

**Comment by boesiii** [comment]
I have a working map, so I just need to write the python code.

In the dialog, would each layer have an option "Add to Basemaps"?

**Comment by tomchadwin** [comment]
Hrm. That's not what I was describing, and it would be a lot more work. If you made the changes I described, it would simply allow you to add your WMS (or whatever) as a custom basemap by editing `basemaps.py` to add it in, (and also adding the matching name into `configparams.py`). That would make your layer appear in the basemaps list.

**Comment by boesiii** [comment]
I didn't read your comment fully but I think I grasp what you are saying.

Wouldnt my WMS url be wipped out after an upgrade?

**Comment by tomchadwin** [comment]
Good point - it would be, as things currently stand. We had the same problem with customized templates being overwritten. We got round that by copying templates out of `.qgis2/python/plugins/qgis2web/templates` into `.qgis2/qgis2web/templates`. We could do the same with basemaps.

**Comment by tomchadwin** [comment]
Thinking about it, this probably isn't worth working on. When 2.18 becomes LTR, the intention is to remove the basemap list from qgis2web completely. In Leaflet/OL terms, I think the *only* difference between a  basemap and a normal QGIS layer is that the layer has a radio button in the layers list instead of a checkbox. If people still require the radio button functionality, we'll have to look at adding a checkbox to each layer - `Basemap`. That would then allow *any* QGIS layer to be a basemap.

Does that sound workable as a plan?

**Comment by tomchadwin** [comment]
In the meantime, all you need to do is add your WMS as a normal layer, export, then edit `index.html` and move your layer into the `basemaps` bit of the `L.control.layers` code.
