### ISSUE TITLE
Leaflet error when no layers loaded in QGIS

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#538]
```
Traceback (most recent call last):
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\maindialog.py", line 318, in previewMap
preview_file = self.createPreview()
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\maindialog.py", line 280, in createPreview
dest_folder=utils.tempFolder()).index_file
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 99, in write
folder=dest_folder)
File "C:/Users/tchadwin/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 295, in writeLeaflet
if cluster[count]:
UnboundLocalError: local variable 'count' referenced before assignment
```

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by jukos** [comment]
Hello,
fine. No error, if I start qgis2web without opening a project.
I am the writer jürgen of
https://gis.stackexchange.com/questions/254801/qgis-2-18-12-qgis2web-error

The other thing was:
"If I start a project and want to use qgis2web: Nothing happens, I see only the hourglass. Then I must restart qgis."
My update to this:
If I check only layers with points or lines: All OK.
If I have checked for example "openstreetmap" or "stamen" or
a layer with srtm datas: No start of qgis2web.
This is for me now not a problem, because I know this. But If somebody not knows this.......he/she could think, qgis2web is down or so....

Thank you and greetings

**Comment by tomchadwin** [comment]
Can you tell me precisely what these layers are which cause it to hang? For instance, how did you open the OpenStreetMap layer in QGIS?

**Comment by jukos** [comment]
Hello,
examples with openlayers: 
- openstreetmap or stamen:  problem: only hourglass 
- Bing Aerial with labels : OK

OSM, Stamen within qgis2web: OK

Wondering:
- 50s090w_20101117_gmted_max075 (digital elevation file from earthexplorer):
1. Waiting.....ca. 30 seconds.....first hourglass than nothing (hourglass is not show), qgis2web is not open
2. Some seconds later: starting qgis2web again: show the layer!

I do more tests, if I could help.
Info: My PC system ist very new and fast. 

Greetings

**Comment by tomchadwin** [comment]
That's why I'm asking how you loaded OSM/Stamen layers. There are many different ways of loading that data into QGIS, and each method will have a different result in qgis2web. If you use eg QuickMapServives, the layer should simply be ignored. If you add it as an XYZ layer, it should export.

If you open *vector* OSM data, qgis2web will try to export it. However, if there is a lot of data, it is unlikely to work, because neither Leaflet nor OpenLayers can display such a huge dataset from a GeoJSON source. It will try, but that will result in a hang.

I'll therefore close this issue. There are limitations on what kind of data can be turned into a web map, and if you try to convert huge datasets using qgis2web, it will likely hang.

**Comment by jukos** [comment]
OK. Thank you for your great plugin!
Greetings
Jürgen
