### ISSUE TITLE
Interactive floor plans

### ISSUE THREAD

**Issue by mbutterz** [tomchadwin/qgis2web#713]
Hi all

I'm currently trying to develop an interactive web map for our office building, which shows the various rooms and equipment etc on each floor. qgis2web seems like the ideal solution, however there's 2 hurdles:

1. Having a static image as the 'base map' (i.e. the floor plans). I've edited the CAD files to style them, then opened them in QGIS. However when I added a few points and tried to export it to the web with with the plugin the image didn't display. Is it not possible to have a PNG file as the 'base map'?

2. If it is possible to have the images with no base map, I would like to be able to select between the individual floors, like on Google maps:

![image](https://user-images.githubusercontent.com/47577758/52670264-fef51400-2f0f-11e9-8154-85dc38f85dd7.png)

Other than have each floor as a separate link, is there a way to achieve this so all the floors are in the same workspace?

Thanks for any help, and if you've got any thoughts on how we could accomplish this i'd really grateful!

Michael

**Comment by tomchadwin** [comment]
You should add your PNG floor images as raster layers in QGIS, and then make sure that you select "Add layers list" in qgis2web. The layers list will allow you to turn layers on and off = eg change floors.

As for why things are not displaying, my first thought would be that it could be a projection issue - can you give us some info? Alternatively, you've triggered a qgis2web error, so please follow the bug reporting steps to try to get the information we require in order to help. Specifically, you'll need to look at the console, either in the qgis2web preview pane, or in the browser displaying the exported map.

**Comment by mbutterz** [comment]
I think I need to play with the coding to get the images to load.

In terms of switching between the floors, what would be the best way to do it? As each floor will have different data on it. Ideally i'd want buttons on the left hand side where you can pick a floor.

**Comment by tomchadwin** [comment]
If it were just the underlying raster floorplans which needed to be switched, you can add a layers list and then make the layers base layers (sadly only by editing the code after export). Base layers are mutually exclusive - when you click one in the layers list to display it, the other(s) turn off. If, however, you have multiple layers each associated with only one of the floors, you'd probably need to look at layer groups. Again, these are not well supported by the plugin, so your best approach might be to export a map with all layers showing, and then edit the code to put each set of layers into "floor" layer groups.

**Comment by boesiii** [comment]
Are you images projected to a coordinate system?

**Comment by boesiii** [comment]
If you attach one of you image files then I can try and use the same data to produce your web map.

**Comment by mbutterz** [comment]
> If you attach one of you image files then I can try and use the same data to produce your web map.

Ok i'll attach a PNG file of one of the floors. They won't need coordinates on them as it won't really be used for navigating. I just want to pick between the floors and see what's on them!

![gf](https://user-images.githubusercontent.com/47577758/52958254-9a144080-338b-11e9-9218-be65a68c6ed2.png)

**Comment by boesiii** [comment]
With a little effort I was able to make an example of your web map, see attached files.  If you turn off the different layers in the expanded layer dropdown you will be able to cycle through each floor plan as needed.

[qgis2web_2019_02_18-11_05_02_804611.zip](https://github.com/tomchadwin/qgis2web/files/2876504/qgis2web_2019_02_18-11_05_02_804611.zip)

**Comment by mbutterz** [comment]
Thanks for that @boesiii - can I ask what steps you took to get there? 
Ideally I don't want a basemap as such - just the image of the floor plans.

**Comment by boesiii** [comment]
Yes but first give me more info about your project.  What are the units (feet or metric)?  I need to know the approximate location so I know what coordinate system (projection) to define.

**Comment by boesiii** [comment]
Also what is the scale of the image?  1"=____ or 1:______

**Comment by mbutterz** [comment]
So does it need a physical geographic location to 'project' the image on to? It can't just be a raster image floating in a blank space?

The location of the building is 450221,275516

**Comment by boesiii** [comment]
Yes.  No.  
When dealing with GIS your data always needs to have a specific coordinate system but we can get away without knowing the exact one.  Here are the steps needed to produce a webmap

1.  make sure to upgrade qgis2web to the latest version

2. Start a new Qgis Project

3. Change the project coordinate system to EPSG:3857

4. Drag image onto the map canvas.  Qgis will ask for the coordinate system, make sure to assign it the same as the project, EPSG: 3857.  Repeat for the other images, keep in mind that you will not be able to see them because they will be stacked.

5.  Start Qgis2web, make sure the box next to "Match Project CRS" is checked.  Also under the appearance tab make the "add layers list" option is set to "Expanded"

6.  Click the export button.  Voila you should have a working webmap.

**Comment by HerbFargus** [comment]
>When dealing with GIS your data always needs to have a specific coordinate system

for leaflet there are ways to create an arbitrary coordinate system without respect to real world locations provided that the features in the map are scaled properly to each other.

eg: https://leafletjs.com/examples/crs-simple/crs-simple.html

Personally if I were in the states I would just use a stateplane coordinate system as those often reflect the  scale of CAD drawings (provided the cad drawings are scaled and georeferenced accordingly in the first place), otherwise it's probably simplest to just use an arbitrary coordinated system specific to the floorplan itself.

**Comment by mbutterz** [comment]
Ok thanks guys, it seems you do need to georeference a raster image for it to generate a web map. 

So with the different floors I think I might try doing them as separate Web maps, and then have links to each one on the page. 

Is there a leaflet plug in maybe which let's you add custom buttons?

**Comment by boesiii** [comment]
Actually no, you don't need to georeference them at all and you can have each image as a different layer and turn off the other floor plan images.  If you want the images to be to exact scale and dimensions then yes you will need to georeference them.

What will the custom buttons do?

**Comment by mbutterz** [comment]
Well they don't show if I don't georeference them... I must still be missing something?

Each floor has different points and data on them, so I can't just switch between the images because that wouldn't change the data.

**Comment by boesiii** [comment]
The key is making sure your project CRS is set to EPSG 3857 and when you drag your images onto the map canvas it will ask what coordinate system, make sure you also set them to EPSG 3857.

Your other problem, changing layers based on another layer, will involve modifying the javascript code index.html after your export from qgis2web.  I only had to add or modify  a few lines, see attached.
[qgis2web_2019_02_20-08_47_22_516294.zip](https://github.com/tomchadwin/qgis2web/files/2884972/qgis2web_2019_02_20-08_47_22_516294.zip)

First I grouped all of the image layers
`var overlayMaps = {layer_level2_0, layer_level1_1};`

Added those as a separate layer control
`L.control.layers(overlayMaps, null, {collapsed:false}).addTo(map);`

Then added a function to the baselayerchange event to turn layers on and off based on the base layer
```
map.on('baselayerchange', function(e) {
            if (e.name == 'layer_level1_1') {
                map.addLayer(layer_lv1_poi_2);
                map.removeLayer(layer_lv2_poi_3);}
            if (e.name == 'layer_level2_0') {
                map.addLayer(layer_lv2_poi_3);
                map.removeLayer(layer_lv1_poi_2);}
                
            <!-- console.log(e.name); -->
        });
```

If you extract my zip file and open index.html in a browser, you will see my sample web map.

**Comment by tomchadwin** [comment]
Just a note: no need to check "Match project CRS" if the project is in EPSG:3857, since that's the default output projection.

Thanks very much to @boesiii and @HerbFargus for helping out here. I hope people don't mind, but I'll close this issue, since it's not really a bug or a feature request. Obviously feel free to continue to discuss here, but [Stack Exchange](https://gis.stackexchange.com/) might be a better bet for such questions in the future.
