### ISSUE TITLE
Update GeoJSON file without running qgis2web

### ISSUE THREAD

**Issue by mb72** [tomchadwin/qgis2web#729]
I'd like to update a geojson file in a qgis2web map, but replacing the existing file with a geojson created by QGIS with identical attribute columns doesn't work. Any thoughts?

**Comment by tomchadwin** [comment]
qgis2web generates JSONP files, not plain JSON. Open a qgis2web one in a text editor, and you'll see the JSON is assigned to a JS variable: https://github.com/tomchadwin/qgis2web/blob/master/qgis2web/utils.py#L245

So you need to do the same, with the same variable name, in order to update the data without reexporting. Let us know if that works for you.
