### ISSUE TITLE
SVG Marker Problem - leaflet 

### ISSUE THREAD

**Issue by gobinathp** [tomchadwin/qgis2web#761]
Hi Developers,

I'm using the updated qgis2web plugin 3.7.0, but I'm getting the round symbol instead of my customised *.SVG, 

![image](https://user-images.githubusercontent.com/6542202/59845049-0d4db380-937a-11e9-92f8-a85d6baea776.png)

Note: in qgis2web OpenLayers measurement control is not working properly, so for the interactive measurement control I moved to Leaflet, but I'm getting SVG issues

**can someone help to solve this issues**
 @tomchadwin

**Comment by tomchadwin** [comment]
Can you upload your project, layer, and SVG files? Can you also open another issue for the OpenLayers measurement issue, and give some more details there?

**Comment by gobinathp** [comment]
@tomchadwin **thanks for your timely response**, I was out-of-station couldn't reply to you on the proper time. here are the files in *.zip format.

[#761_SVG_Marker_Problem.zip](https://github.com/tomchadwin/qgis2web/files/3326036/761_SVG_Marker_Problem.zip)

Thanks.

**Comment by gobinathp** [comment]
@tomchadwin is that files are fine? any problems with file for getting the symbol issues?

**Comment by tomchadwin** [comment]
Thanks for your patience. I can see the issue, yes. I don't know the cause yet, but shall investigate.

**Comment by tomchadwin** [comment]
I can see the issue here. Non-SVG symbology is created in Leaflet via eg `L.circleMarker`, whereas SVGs are via `L.marker`. The issue here is that, because you are using a categorized symbol renderer, you have both SVGs and circles in one layer. That layer can only be exported as either `L.circleMarker` *or* `L.marker`, but not both. What is happening in your example is that it is using `L.circleMarker`, and hence is trying to assign SVG style information to a circle. None of the properties are therefore valid, and Leaflet applies a default style to the circle instead.

I'm not really sure I can find a solution to this in qgis2web, so I can only suggest a workaround: separate the different categories into different layers.

**Comment by gobinathp** [comment]
Yeah @tomchadwin., no issues. Thanks for your reply. I'll try other best possible solutions to make it happen.
