### ISSUE TITLE
problem with exporting

### ISSUE THREAD

**Issue by critgeo** [tomchadwin/qgis2web#862]
Hello, 

thank you for your work

I have tried to see whether the issue has already been reported, but the answers do not seem to help me so much. 

So, when I try to export nothing appears on the preview and nothing comes out if i export the file. So far, the only solution I found is to change to single symbol, and it worked. With the new map I am making this solution does not work anymore, even if it is on single symbol. 

Moreover, it would be nice to implement the rule based symbol, although I have no idea how difficult this might be.

Thank you for your time!

**Comment by tomchadwin** [comment]
I'm afraid that's not enough for us to investigate. Can you upload you project and layer files?

**Comment by critgeo** [comment]
So, it is literally just a CSV [https://github.com/critgeo/critgeo.github.io/blob/master/Agrigento%20MSNA%20-%20Sheet1.csv] and open street map layer. This time it does not work even if i don't do any processing (although most of the processing tools do work with qgistoweb)

**Comment by tomchadwin** [comment]
We really need the files - your project file saves your settings from the qgis2web dialog, and other QGIS project settings all of which change the way in which qgis2web works.

**Comment by critgeo** [comment]
this is the output of qgis2web https://github.com/critgeo/critgeo.github.io/tree/master/qgis2web_2020_04_06-17_07_02_808906

and this is the project

https://github.com/critgeo/critgeo.github.io/blob/master/mappa.qgz

**Comment by tomchadwin** [comment]
OK, three issues here:

1. qgis2web was not handling apostrophes in field names correctly. I've made a commit to master to fix this.
2. You need to give your project a projection - I set it to EPSG:3857.
3. There is a bug with the layer search which I have not yet understood or fixed.

So, copy down master branch from here to get the fix for 1, give your project a projection such as EPSG:3857, and temporarily set Appearance > Layer search to None until I can figure out that issue. That allows the map to export for me - let me know how it goes.

**Comment by critgeo** [comment]
Yes! perfectly working now. I don't know why it seemed that I did not give a projection! But yes amazing, working perfectly!

**Comment by tomchadwin** [comment]
Brilliant. Thanks for finding and reporting the bug, and for testing the fix. I will look into the search issue, too, but I might open a new issue for that.

**Comment by tomchadwin** [comment]
Released as 3.13.0 and pushed to QGIS plugins repo.
