### ISSUE TITLE
Broken hash function 

### ISSUE THREAD

**Issue by nirvine** [tomchadwin/qgis2web#914]
Versions:
QGIS 3.4.15-Madeira
qgis2web 3.16.0
Browsers checked: Firefox and Chrome
Previous reporting of this bug: #842 
Published map: https://khuts.org/webmap

If I add the lat/long and zoom to a link, the map jumps to the default position. 
eg. https://khuts.org/webmap/index.html#16/-36.2162/148.4676
This should zoom in to Kidmans Hut.

**Comment by tomchadwin** [comment]
It's because you have set the options `Appearance > Scale/Zoom > Extent` to "Fit to layers extent". In Leaflet, this works by rezooming and panning the map when it has finished loading, to ensure it displays the full extent of all your project layers, thereby zooming/panning away from your hash location. Try changing the setting to "Canvas extent", and zoom/pan in QGIS to get a good initial extent (when you give no hash position.

Hope this makes sense.
