### ISSUE TITLE
Large GeoTiffs not exporting

### ISSUE THREAD

**Issue by Mikester-Calgary** [tomchadwin/qgis2web#956]

**Comment by tomchadwin** [comment]
There are a few issues here:

- What do you mean "tiles up to 16x? What kind of layer are they in your QGIS project?
- Large rasters Just Won't Work - qgis2web is designed to create webmaps, and webmaps don't thrown 2GB fies around, as they could not effectively be downloaded.
- Rasters are converted to RBG PNGs so that they will render in a browser - that means that raster values are lost. However, do I assume that your original TIFFs are visible in your QGIS project? That style shoud export. It might just be that the raster won't load because it is too big - have a look at your browser console for errors (hit F12)

**Comment by Mikester-Calgary** [comment]
Tom:

Thanks for the response;  I meant pyramids 2 4 8 16 not tile, sorry.

Yes, all are GeoTiff in my QGIS project.

Good advice all.

Thanks.

m

**Comment by tomchadwin** [comment]
OK, pyramids won't help, I'm afraid. You'll need to tile your raster(s) for them to be usable.

**Comment by Mikester-Calgary** [comment]
The GeoTiffs were tiled internally for sure.  Not sure how that helps once they get exported to pngs.

If you have 280 GeoTiff tiles won’t you get 280 layers in your html too?
